In [65]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

In [66]:
file_path = 'NATOPS_sid20-C_TRAIN_su.csv'  
natops_data = pd.read_csv(file_path)

In [67]:
natops_data

,isTest,fea2,fea3,fea4,fea5,fea6,fea7,fea8,fea9,fea10,...,fea14,fea15,fea16,fea17,fea18,fea19,fea20,fea21,sid,class
0,0,0.117647,0.039216,0.0,0.137255,0.019608,0.098039,0.294118,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.137255,0.0,0.0,0.0,1,3
1,0,0.117647,0.039216,0.0,0.137255,0.019608,0.098039,0.294118,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.137255,0.0,0.0,0.0,1,3
2,0,0.117647,0.039216,0.0,0.137255,0.019608,0.098039,0.294118,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.137255,0.0,0.0,0.0,1,3
3,0,0.117647,0.039216,0.0,0.137255,0.019608,0.098039,0.294118,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.137255,0.0,0.0,0.0,1,3
4,0,0.117647,0.039216,0.0,0.137255,0.019608,0.098039,0.294118,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.137255,0.0,0.0,0.0,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18355,1,0.215686,0.000000,0.0,0.196078,0.078431,0.156863,0.000000,0.0,0.0,...,0.0,0.0,0.078431,0.098039,0.156863,0.0,0.0,0.0,360,3
18356,1,0.215686,0.000000,0.0,0.196078,0.078431,0.156863,0.000000,0.0,0.0,...,0.0,0.0,0.078431,0.098039,0.156863,0.0,0.0,0.0,360,3
18357,1,0.215686,0.000000,0.0,0.196078,0.078431,0.156863,0.000000,0.0,0.0,...,0.0,0.0,0.078431,0.098039,0.156863,0.0,0.0,0.0,360,3
18358,1,0.215686,0.000000,0.0,0.196078,0.078431,0.156863,0.000000,0.0,0.0,...,0.0,0.0,0.078431,0.098039,0.156863,0.0,0.0,0.0,360,3
18359,1,0.215686,0.000000,0.0,0.196078,0.078431,0.156863,0.000000,0.0,0.0,...,0.0,0.0,0.078431,0.098039,0.156863,0.0,0.0,0.0,360,3

In [68]:
data_processed = natops_data.drop(['isTest'], axis=1)

In [69]:
data_processed = data_processed.drop(['sid'], axis=1)

In [70]:
data_processed.to_csv("data_processed.csv", index=False)

In [76]:
features = data_processed.drop(['class'], axis=1)

In [72]:
target = data_processed['class']

In [73]:
k_folds = KFold(n_splits = 5)
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('classifier', RandomForestClassifier(random_state=42))
])

In [74]:
scores = cross_val_score(pipeline, features, target, cv= k_folds)

In [75]:
scores

array([0.66666667, 0.70833333, 0.59722222, 0.72222222, 0.66666667])